# Generated by Django 5.0.4 on 2024-06-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instancias',
            fields=[
                ('id_instancia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'instancia',
                'verbose_name_plural': 'instancias',
                'db_table': 'INSTANCIAS',
                'ordering': ('id_instancia',),
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='comportamientos',
            options={'managed': False, 'ordering': ('id_comportamiento',), 'verbose_name': 'comportamiento', 'verbose_name_plural': 'comportamientos'},
        ),
        migrations.AlterModelOptions(
            name='ejecucioneslog',
            options={'managed': False, 'ordering': ('id_ejecucion',), 'verbose_name': 'EJECUCIONES LOG', 'verbose_name_plural': 'EJECUCIONES LOG'},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': False, 'ordering': ('id_estado',), 'verbose_name': 'estado', 'verbose_name_plural': 'estados'},
        ),
        migrations.AlterModelOptions(
            name='frecuencias',
            options={'managed': False, 'ordering': ('id_frecuencia',), 'verbose_name': 'frecuencia', 'verbose_name_plural': 'frecuencias'},
        ),
        migrations.AlterModelOptions(
            name='mediaciones',
            options={'managed': False, 'ordering': ('id_mediacion',), 'verbose_name': 'mediación', 'verbose_name_plural': 'mediaciones'},
        ),
        migrations.AlterModelOptions(
            name='procesos',
            options={'managed': False, 'ordering': ('id_proceso',), 'verbose_name': 'proceso', 'verbose_name_plural': 'procesos'},
        ),
        migrations.AlterModelOptions(
            name='procesossam',
            options={'managed': False, 'ordering': ('id_proceso_sam',), 'verbose_name': 'Procesos SAM', 'verbose_name_plural': 'Procesos SAM'},
        ),
        migrations.AlterModelOptions(
            name='programas',
            options={'managed': False, 'ordering': ('id_programa',), 'verbose_name': 'programa', 'verbose_name_plural': 'programas'},
        ),
        migrations.AlterModelOptions(
            name='tipos',
            options={'managed': False, 'ordering': ('id_tipo',), 'verbose_name': 'tipo', 'verbose_name_plural': 'tipos'},
        ),
        migrations.AlterModelOptions(
            name='uom',
            options={'managed': False, 'ordering': ('id_uom',), 'verbose_name': 'Uom', 'verbose_name_plural': 'Uom'},
        ),
        migrations.AlterModelOptions(
            name='variables',
            options={'managed': False, 'ordering': ('id_variable',), 'verbose_name': 'Variable', 'verbose_name_plural': 'Variables'},
        ),
        migrations.AlterModelOptions(
            name='variablesfactor',
            options={'managed': False, 'ordering': ('id_variable_factor',), 'verbose_name': 'Variable Factor', 'verbose_name_plural': 'Variables Factor'},
        ),
    ]
